### PR TITLE
Added check for missing/different TemplateURL field in docker template

### PR DESCRIPTION
**Pull request by jlesage**
The `TemplateURL` field inside unRAID's docker template is useful, because it provides a way for the author to push updates to its template(s).  Providing updates is useful to fix descriptions, default values, adding new settings, etc.

This pull request is for adding a check to *Fix Common Problems* plugin, to make sure that installed templates have the correct TemplateURL field.  This check is useful in scenarios where the author adds a TemplateURL after users installed the application.

### CODE REVIEW

**Comment by Squidly271** [comment]
What existing template is missing this so I can test?

**Comment by jlesage** [comment]
You can install any docker container from my repository.  They all have the `TemplateURL` field set.

Then manually edit the installed template (`/boot/config/plugins/dockerMan/templates-user/my-*.xml`) by changing the `TemplateURL`: You can clear it (change to `<TemplateURL/>`) or change the existing value to anything.

Then run FCP checks.

**Comment by Squidly271** [comment]
Merged.  Your txz had all the executable permissions missing for some reason

**Comment by jlesage** [comment]
Thanks Squid.  Could you tell me which method you use to build the package?  Slackware's makepkg?  What if I'm working on Ubuntu?  I used an alternative to Slackware's makepkg...

**Comment by Squidly271** [comment]
makepkg -l y -c y

**Comment by jlesage** [comment]
In fact my question was more where `makepkg` is coming from if we are not working with Slackware?

**Pull request merged**
